-- PRIMARY KEY & FOREIGN KEY --
CREATE DATABASE BOOKSTORE;
USE BOOKSTORE;
CREATE TABLE Books
(Book_ID INT PRIMARY KEY,
Book_Name VARCHAR (150));
SELECT * FROM Books;
CREATE TABLE Orders
(Order_ID INT PRIMARY KEY,
Customer_Name VARCHAR (100),
Book_ID INT,
FOREIGN KEY (Book_ID) REFERENCES Books(Book_ID));
SELECT * FROM Orders;

-- UNIQUE Constraint --
ALTER TABLE Books
ADD COLUMN ISBN INT;
ALTER TABLE Books
ADD CONSTRAINT unique_ISBN UNIQUE (ISBN);

-- DELETE & TRUNCATE --
DELETE from Orders WHERE Order_ID< 10 ;
TRUNCATE TABLE Orders;








